### ISSUE TITLE
Remove `List` from `src/core`

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#336]
## Move `List` out of `src/core`

**location:** 'src/core/List.js'
**description:**
There is the only reason `List` is in `core` is for some specs and use in `src/Pair/toPairs`. It actually makes more sense to have `toPairs` return an Array of Pairs. With that done

### Task List

* [ ] Alter `toPairs` to return `Array` instead `List`
* [ ] Remove/Replace specs using `List` inside of `src/Async/Async.spec.js`
* [ ] Remove/Replace specs using `List` inside of `src/Maybe/find.spec.js`
* [ ] Move implementation from `src/core/List.js` and `src/core/List.spec.js` to `src/List/index.js` and `src/List/List.spec.js`
* [ ] Update the documentation
