### ISSUE TITLE
Move `fanout` to `src/Pair`

### ISSUE THREAD

**Issue by evilsoft** [evilsoft/crocks#337]
### Description/Location

**location:** 'src/helpers/fanout.js'
**description:**
`fanout` is out of place from our pattern of putting functions into the folders of the type they return/construct outside of normal JS types. As `fanout` NEEDS to have a `Pair` it should live inside of `src/Pair`.

### Task List

* [ ] move `fanout` from `src/helpers/fanout.js` into `src/Pair`
* [ ] move `fanout` from `src/helpers/fanout.spec.js` into `src/Pair`
* [ ] Update references to main api references
* [ ] Update the documentation

For more information, see the `CONTRIBUTING` guide.

**Comment by evilsoft** [comment]
it has not shipped yet. I like to keep them open until released.

**Comment by rpearce** [comment]
Got it! Thanks for clarifying

**Comment by evilsoft** [comment]
Is now in production!
Closing!
