### ISSUE TITLE
Add documentation for the `Unit` crock

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#378]
### Description

To bring it in-line with the other `Crocks` we need to add in descriptive documentation for the `IO` crock with examples

### Task List

* [ ] Add main `Unit.md` file to 'docs/src/pages/docs/crocks/' based on the others
* [ ] Ensure it has the correct 'weight'
* [ ] Locate all references to `Unit` and update it to link to the new `Unit` documentation. Reference the section where possible
* [ ] Update `docs/src/pages/docs/crocks/index.md` with links to the new `Unit.md` page
* [ ] Update `docs/src/pages/docs/functions/pointfree-functions.md` with links to the new `Unit.md` page

For more information, see the [`CONTRIBUTING`][contributing] guide.

### Further Information

This was sourced from https://github.com/evilsoft/crocks/issues/42

[contributing]: https://github.com/evilsoft/crocks/blob/master/CONTRIBUTORS.md
