### ISSUE TITLE
Add documentation for the `Writer` crock

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#379]
### Description

To bring it in-line with the other `Crocks` we need to add in descriptive documentation for the `Writer` crock with examples

### Task List

* [ ] Add main `Writer.md` file to 'docs/src/pages/docs/crocks/' based on the others
* [ ] Ensure it has the correct 'weight'
* [ ] Locate all references to `Writer` and update it to link to the new `Writer` documentation. Reference the section where possible
* [ ] Update `docs/src/pages/docs/crocks/index.md` with links to the new `Writer.md` page
* [ ] Update `docs/src/pages/docs/functions/pointfree-functions.md` with links to the new `Writer.md` page

For more information, see the [`CONTRIBUTING`][contributing] guide.

### Further Information

This was sourced from https://github.com/evilsoft/crocks/issues/42
We may want to hold off on writing this until https://github.com/evilsoft/crocks/issues/201 is complete as it'll change the behaviour

[contributing]: https://github.com/evilsoft/crocks/blob/master/CONTRIBUTORS.md
